services:
  node-app:
    build: .
    ports:
      - "8081:8080" # Changed to 8081 to avoid conflicts
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - kanban-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090" # Changed to 9091 to avoid conflicts
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    networks:
      - kanban-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - kanban-network

volumes:
  grafana-data:

networks:
  kanban-network:
    driver: bridge
